name: Setup Bun and install dependencies
description: Setup Bun, restore cache, and install dependencies
runs:
  using: composite
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - name: Cache Bun
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
          node_modules
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash
